### ISSUE TITLE
Zoeken op voornaam/foto mogelijk maken

### ISSUE THREAD

**Issue by jamy015** [Mentoraat/preferences-site#1]
Met het systeem dat er nu is, moet je steeds aan mensen vragen wat hun NetID is. Het zou handiger zijn als je op voornaam kon zoeken, en misschien ook op foto als er meerdere mensen met die voornaam zijn.

**Comment by TimvdLippe** [comment]
Searching on first name is indeed a desired feature.
Regarding photos, there are quite some hassles accompanied with this feature. For example privacy and storage.

We also have to cope with the problem that most of the information is not available yet or has to be retrieved from external (university-wide) systems, which makes development a lot harder. This would in addition increase the amount of manual labour that has to be put in each year to retrieve and transfer this data.

**Comment by jwgmeligmeyling** [comment]
Any student at the university is allowed to see netId/firstname/lastname data for any TU worker or student, and this information can be retrieved through the Active Directory server. You would however have to login on to the AD using the users credentials or have an application specific login for the AD... I think even if we ever will have access to SAML or the OData API's this is still the only way to retrieve data such as names of other students, unless you have this data in your own database obviously. 

Example query:

``` sh
ldapsearch -H "ldaps://ldaps.tudelft.nl:636" -LLL -D "jgmeligmeyling@tudelft.net" -W -b "OU=MDS,DC=tudelft,DC=net" "(&(givenName=Jan-Willem)(sn=Gmelig*))" givenName sn uid mail
```

(The user at `-D` should be an account that you know the password for, the password will be prompted after executing the command, thats what the `-W` option is for, example uses `ldapsearch` but there are LDAP clients for php)

Outputs:

```
dn: CN=Gmelig Meyling\, J. (jgmeligmeyling),OU=Students,OU=MDS,DC=tudelft,DC=net
sn: Gmelig Meyling
givenName: Jan-Willem
uid: jgmeligmeyling
mail: ...
```

**Comment by TimvdLippe** [comment]
Closing this as a wontfix.
